// Generated from CelesTrak SATCAT lookup tables (celestrak.org/satcat/sources.php, launchsites.php).

export const OWNERS: Record<string, { name: string; flag?: string }> = {
  "AB": { name: "Arabsat" },
  "ABS": { name: "Asia Broadcast Satellite" },
  "AC": { name: "AsiaSat" },
  "ALG": { name: "Algeria", flag: "dz" },
  "ANG": { name: "Angola", flag: "ao" },
  "ARGN": { name: "Argentina", flag: "ar" },
  "ARM": { name: "Armenia", flag: "am" },
  "ASRA": { name: "Austria", flag: "at" },
  "AUS": { name: "Australia", flag: "au" },
  "AZER": { name: "Azerbaijan", flag: "az" },
  "BEL": { name: "Belgium", flag: "be" },
  "BELA": { name: "Belarus", flag: "by" },
  "BERM": { name: "Bermuda", flag: "bm" },
  "BGD": { name: "Bangladesh", flag: "bd" },
  "BHR": { name: "Bahrain", flag: "bh" },
  "BHUT": { name: "Bhutan", flag: "bt" },
  "BOL": { name: "Bolivia", flag: "bo" },
  "BRAZ": { name: "Brazil", flag: "br" },
  "BUL": { name: "Bulgaria", flag: "bg" },
  "BWA": { name: "Botswana", flag: "bw" },
  "CA": { name: "Canada", flag: "ca" },
  "CHBZ": { name: "China/Brazil" },
  "CHTU": { name: "China/Türkiye" },
  "CHLE": { name: "Chile", flag: "cl" },
  "CIS": { name: "Russia / former USSR", flag: "ru" },
  "COL": { name: "Colombia", flag: "co" },
  "CRI": { name: "Costa Rica", flag: "cr" },
  "CZCH": { name: "Czech Republic", flag: "cz" },
  "DEN": { name: "Denmark", flag: "dk" },
  "DJI": { name: "Djibouti", flag: "dj" },
  "ECU": { name: "Ecuador", flag: "ec" },
  "EGYP": { name: "Egypt", flag: "eg" },
  "ESA": { name: "European Space Agency" },
  "ESRO": { name: "European Space Research Organization" },
  "EST": { name: "Estonia", flag: "ee" },
  "ETH": { name: "Ethiopia", flag: "et" },
  "EUME": { name: "EUMETSAT" },
  "EUTE": { name: "Eutelsat" },
  "FGER": { name: "France/Germany" },
  "FIN": { name: "Finland", flag: "fi" },
  "FR": { name: "France", flag: "fr" },
  "FRIT": { name: "France/Italy" },
  "GER": { name: "Germany", flag: "de" },
  "GHA": { name: "Ghana", flag: "gh" },
  "GLOB": { name: "Globalstar" },
  "GREC": { name: "Greece", flag: "gr" },
  "GRSA": { name: "Greece/Saudi Arabia" },
  "GUAT": { name: "Guatemala", flag: "gt" },
  "HRV": { name: "Croatia", flag: "hr" },
  "HUN": { name: "Hungary", flag: "hu" },
  "IM": { name: "Inmarsat" },
  "IND": { name: "India", flag: "in" },
  "INDO": { name: "Indonesia", flag: "id" },
  "IRAN": { name: "Iran", flag: "ir" },
  "IRAQ": { name: "Iraq", flag: "iq" },
  "IRID": { name: "Iridium" },
  "IRL": { name: "Ireland", flag: "ie" },
  "ISRA": { name: "Israel", flag: "il" },
  "ISRO": { name: "Indian Space Research Organisation", flag: "in" },
  "ISS": { name: "International partnership (NASA, Roscosmos, ESA, JAXA, CSA)" },
  "IT": { name: "Italy", flag: "it" },
  "ITSO": { name: "Intelsat" },
  "JPN": { name: "Japan", flag: "jp" },
  "KAZ": { name: "Kazakhstan", flag: "kz" },
  "KEN": { name: "Kenya", flag: "ke" },
  "LAOS": { name: "Laos", flag: "la" },
  "LKA": { name: "Sri Lanka", flag: "lk" },
  "LTU": { name: "Lithuania", flag: "lt" },
  "LUXE": { name: "Luxembourg", flag: "lu" },
  "MA": { name: "Morocco", flag: "ma" },
  "MALA": { name: "Malaysia", flag: "my" },
  "MCO": { name: "Monaco", flag: "mc" },
  "MDA": { name: "Moldova", flag: "md" },
  "MEX": { name: "Mexico", flag: "mx" },
  "MMR": { name: "the Union of Myanmar", flag: "mm" },
  "MNE": { name: "Montenegro", flag: "me" },
  "MNG": { name: "Mongolia", flag: "mn" },
  "MUS": { name: "Mauritius", flag: "mu" },
  "NATO": { name: "North Atlantic Treaty Organization" },
  "NETH": { name: "Netherlands", flag: "nl" },
  "NICO": { name: "New ICO" },
  "NIG": { name: "Nigeria", flag: "ng" },
  "NKOR": { name: "North Korea", flag: "kp" },
  "NOR": { name: "Norway", flag: "no" },
  "NPL": { name: "Nepal", flag: "np" },
  "NZ": { name: "New Zealand", flag: "nz" },
  "O3B": { name: "O3b Networks" },
  "ORB": { name: "ORBCOMM" },
  "PAKI": { name: "Pakistan", flag: "pk" },
  "PERU": { name: "Peru", flag: "pe" },
  "POL": { name: "Poland", flag: "pl" },
  "POR": { name: "Portugal", flag: "pt" },
  "PRC": { name: "China", flag: "cn" },
  "PRY": { name: "Paraguay", flag: "py" },
  "PRES": { name: "People's Republic of China/European Space Agency" },
  "QAT": { name: "Qatar", flag: "qa" },
  "RASC": { name: "RascomStar-QAF" },
  "ROC": { name: "Taiwan", flag: "tw" },
  "ROM": { name: "Romania", flag: "ro" },
  "RP": { name: "Philippines", flag: "ph" },
  "RWA": { name: "Rwanda", flag: "rw" },
  "SAFR": { name: "South Africa", flag: "za" },
  "SAUD": { name: "Saudi Arabia", flag: "sa" },
  "SDN": { name: "Sudan", flag: "sd" },
  "SEAL": { name: "Sea Launch" },
  "SEN": { name: "Senegal", flag: "sn" },
  "SES": { name: "SES" },
  "SGJP": { name: "Singapore/Japan" },
  "SING": { name: "Singapore", flag: "sg" },
  "SKOR": { name: "South Korea", flag: "kr" },
  "SLB": { name: "Solomon Islands", flag: "sb" },
  "SPN": { name: "Spain", flag: "es" },
  "STCT": { name: "Singapore/Taiwan" },
  "SVN": { name: "Slovenia", flag: "si" },
  "SWED": { name: "Sweden", flag: "se" },
  "SWTZ": { name: "Switzerland", flag: "ch" },
  "TBD": { name: "To Be Determined" },
  "THAI": { name: "Thailand", flag: "th" },
  "TMMC": { name: "Turkmenistan/Monaco" },
  "TUN": { name: "Tunisia", flag: "tn" },
  "TURK": { name: "Türkiye", flag: "tr" },
  "UAE": { name: "United Arab Emirates", flag: "ae" },
  "UK": { name: "United Kingdom", flag: "gb" },
  "UKR": { name: "Ukraine", flag: "ua" },
  "UNK": { name: "Unknown" },
  "URY": { name: "Uruguay", flag: "uy" },
  "US": { name: "United States", flag: "us" },
  "USBZ": { name: "United States/Brazil" },
  "VAT": { name: "Vatican City State", flag: "va" },
  "VENZ": { name: "Venezuela", flag: "ve" },
  "VTNM": { name: "Vietnam", flag: "vn" },
  "ZWE": { name: "Zimbabwe", flag: "zw" },
};

export const LAUNCH_SITES: Record<string, string> = {
  "AFETR": "Cape Canaveral / Kennedy Space Center, Florida, USA",
  "AFWTR": "Vandenberg Space Force Base, California, USA",
  "ANDSP": "Andøya Spaceport, Nordland, Norway",
  "ALCLC": "Alâcantara Launch Center, Maranhão, Brazil",
  "BOS": "Bowen Orbital Spaceport, Queensland, Australia",
  "CAS": "Canaries Airspace",
  "DLS": "Dombarovskiy Launch Site, Russia",
  "ERAS": "Eastern Range Airspace",
  "FRGUI": "Europe's Spaceport, Kourou, French Guiana",
  "HGSTR": "Hammaguira Space Track Range, Algeria",
  "JJSLA": "Jeju Island Sea Launch Area, Republic of Korea",
  "JSC": "Jiuquan Satellite Launch Center, PRC",
  "KODAK": "Kodiak Launch Complex, Alaska, USA",
  "KSCUT": "Uchinoura Space Center, Japan",
  "KWAJ": "Kwajalein Atoll, Marshall Islands",
  "KYMSC": "Kapustin Yar Missile and Space Complex, Russia",
  "NSC": "Naro Space Complex, Republic of Korea",
  "PLMSC": "Plesetsk Cosmodrome, Russia",
  "RLLB": "Rocket Lab Launch Base, Mahia Peninsula, New Zealand",
  "SCSLA": "South China Sea Launch Area, PRC",
  "SEAL": "Sea Launch Platform (mobile)",
  "SEMLS": "Semnan Satellite Launch Site, Iran",
  "SMTS": "Shahrud Missile Test Site, Iran",
  "SNMLP": "San Marco Launch Platform, Indian Ocean (Kenya)",
  "SPKII": "Space Port Kii, Japan",
  "SRILR": "Satish Dhawan Space Centre, Sriharikota, India",
  "SUBL": "Submarine Launch Platform (mobile)",
  "SVOBO": "Svobodnyy Launch Complex, Russia",
  "TAISC": "Taiyuan Satellite Launch Center, PRC",
  "TANSC": "Tanegashima Space Center, Japan",
  "TYMSC": "Baikonur Cosmodrome, Kazakhstan",
  "UNK": "Unknown",
  "VOSTO": "Vostochny Cosmodrome, Russia",
  "WLPIS": "Wallops Island, Virginia, USA",
  "WOMRA": "Woomera, Australia",
  "WRAS": "Western Range Airspace",
  "WSC": "Wenchang Satellite Launch Site, PRC",
  "XICLF": "Xichang Satellite Launch Center, PRC",
  "YAVNE": "Yavne Launch Facility, Israel",
  "YSLA": "Yellow Sea Launch Area, PRC",
  "YUN": "Sohae Satellite Launching Station, North Korea",
};
